//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListClientOrder
    {
        public int Id { get; set; }
        public Nullable<int> ClientOrderId { get; set; }
        public Nullable<int> FlowerId { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<double> Sum { get; set; }
    
        public virtual ClientOrder ClientOrder { get; set; }
        public virtual Flower Flower { get; set; }
    }
}
